### ISSUE TITLE
[WINDOWS]: ERROR: C++ shared or static library 'atomic' not found 

### ISSUE THREAD

**Issue by shipleyxie** [mesonbuild/abseil-cpp#10] opened 2021-07-27 16:32 UTC
I want to generate visual studio solution folder, but got 

> $ meson setup build_vs --backend=vs2019
> The Meson build system
> Version: 0.59.0
> Source dir: D:\
> Build dir: D:\build_vs
> Build type: native build
> Project name: webrtc-audio-processing
> Project version: 1.1
> C compiler for the host machine: cl (msvc 19.29.30038.1 "���� x64 �� Microsoft (R) C/C++ �Ż������� 19.29.30038.1 ��")
> C linker for the host machine: link link 14.29.30038.1
> C++ compiler for the host machine: cl (msvc 19.29.30038.1 "���� x64 �� Microsoft (R) C/C++ �Ż������� 19.29.30038.1 ��")
> C++ linker for the host machine: link link 14.29.30038.1
> Host machine cpu family: x86_64
> Host machine cpu: x86_64
> 
> Executing subproject abseil-cpp
> 
> abseil-cpp| Project name: abseil-cpp
> abseil-cpp| Project version: 20210324.1
> abseil-cpp| C++ compiler for the host machine: cl (msvc 19.29.30038.1 "���� x64 �� Microsoft (R) C/C++ �Ż������� 19.29.30038.1 ��")
> abseil-cpp| C++ linker for the host machine: link link 14.29.30038.1
> abseil-cpp| Compiler for C++ supports arguments -Wno-sign-compare: NO
> abseil-cpp| Compiler for C++ supports arguments -maes: NO
> abseil-cpp| Compiler for C++ supports arguments -msse4.1: NO
> abseil-cpp| Checking if "GCC atomic builtins" links: NO
> 
> subprojects\abseil-cpp\meson.build:36:2: ERROR: C++ shared or static library 'atomic' not found

Could you please give some suggestion?

**Comment by jpakkane** [comment] 2021-07-27 18:50
Have you updated your version with  `meson wrap update`? This should have been fixed a few days ago.

Also, this is a legacy repo. All bugs should be filed against the `mesonbuild/wrapdb` repo. Closing this. If the issue is not fixed by an update, please file a new bug report on that repo.

**Closed as completed by jpakkane** 2021-07-27 18:50 UTC

**Comment by 1728566657** [comment] 2024-04-15 06:42
Boss, how did you solve the problem？
